### ISSUE TITLE
Support Windows and MacOS

### ISSUE THREAD

**Issue by viviag** [pandora-mccme/dbmonitor#9]

**Comment by aeifn** [comment]
Fix for ffi in macOS (arm64)
export C_INCLUDE_PATH="`xcrun --show-sdk-path`/usr/include/ffi"
RUN stack setup
RUN stack install --local-bin-path .

But without inotify it still doesn't build completely.

**Comment by viviag** [comment]
Solution I'm going to implement is to migrate to [higher level interface](https://hackage.haskell.org/package/fsnotify-0.3.0.1)

It solves two problems:
1. Cross-platformity.
2. Recursive directory watches, which is not supported by hinotify.

**Comment by viviag** [comment]
Regarding specific case -- it will die on a start anyway.

**Comment by aeifn** [comment]
Now compiles on macOS (arm64)

**Comment by viviag** [comment]
Did you try to run the program then?
